title: cric-peace
description: Tired of "Was that 4 balls or 5? No more dodgy math or heated debates. This is a simple web app to track scorecard of a cricket match ball by ball! Hopefully it will bring some peace to gully cricket community :) Cheers! 

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
theme: jekyll-theme-cayman
